// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateServiceProps struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int    `json:"price"`
}

type SafeUser struct {
	ID        int          `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt *time.Time   `json:"updatedAt"`
	DeletedAt *time.Time   `json:"deletedAt"`
	Tokens    []*UserToken `json:"tokens"`
	Services  []*Service   `json:"services"`
}

type Service struct {
	ID          int        `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Price       int        `json:"price"`
	UserID      int        `json:"userId"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   *time.Time `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
}

type SignInProps struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpProps struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateServiceProps struct {
	ServiceID   int    `json:"serviceId"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int    `json:"price"`
}

type User struct {
	ID        int          `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt *time.Time   `json:"updatedAt"`
	DeletedAt *time.Time   `json:"deletedAt"`
	Tokens    []*UserToken `json:"tokens"`
	Services  []*Service   `json:"services"`
}

type UserToken struct {
	ID        int        `json:"id"`
	UserID    int        `json:"userId"`
	Token     string     `json:"token"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
}
