// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/d0kur0/cui-server/graph/scalars"
)

type Service struct {
	ID          int        `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Price       int        `json:"price"`
	UserID      int        `json:"userId"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   *time.Time `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
}

type SignInProps struct {
	Email    scalars.Email    `json:"email"`
	Password scalars.Password `json:"password"`
}

type SignUpProps struct {
	Name     scalars.Username `json:"name"`
	Email    scalars.Email    `json:"email"`
	Password scalars.Password `json:"password"`
}

type User struct {
	ID        int              `json:"id"`
	Name      scalars.Username `json:"name"`
	Email     scalars.Email    `json:"email"`
	Password  string           `json:"password"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt *time.Time       `json:"updatedAt"`
	DeletedAt *time.Time       `json:"deletedAt"`
	Tokens    []*UserToken     `json:"tokens"`
	Services  []*Service       `json:"services"`
}

type UserToken struct {
	ID        int        `json:"id"`
	UserID    int        `json:"userId"`
	Token     string     `json:"token"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
}
